---
kind: Secret
apiVersion: v1
metadata:
  name: customized-db-cred
data:
  user_name: SEFORFNPTg== # echo -n 'HANDSON' | base64
  password: V2VsY29tZTEyMzQ1 # echo -n 'Welcome12345' | base64
---
kind: Service
apiVersion: v1
metadata:
  name: oke-atp-helidon
  labels:
    app: oke-atp-helidon
spec:
  type: NodePort
  selector:
    app: oke-atp-helidon
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oke-atp-helidon
spec:
  selector:
    matchLabels:
      app: oke-atp-helidon
  replicas: 1
  template:
    metadata:
      labels:
        app: oke-atp-helidon
        version: v1
    spec:
      # The credential files in the secret are base64 encoded twice and hence they need to be decoded for the programs to use them.
      # This decode-creds initContainer takes care of decoding the files and writing them to a shared volume from which db-app container
      # can read them and use it for connecting to ATP.
      containers:
      - name: oke-atp-helidon
        image: nrt.ocir.io/sehubjapacprod/workshop/oke-atp-helidon:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: javax_sql_DataSource_workshopDataSource_dataSource_user
          valueFrom:
            secretKeyRef:
              name: customized-db-cred
              key: user_name
        - name: javax_sql_DataSource_workshopDataSource_dataSource_password
          valueFrom:
            secretKeyRef:
              name: customized-db-cred
              key: password
        volumeMounts:
        - name: handson
          mountPath: /db-demo/creds              
      imagePullSecrets:
      - name: workshop-ocirsecret
      volumes:
      - name: handson
        configMap:
          name: okeatp  
---